import { api } from './api.js';
import { pageShell, requireOperator, operator, setOperator, escapeHtml, money, time, statusClass, showError, confirmDialog } from './app.js';

const page = document.body.dataset.page;
const app = document.querySelector('#app');
if (page !== 'customer' && !requireOperator()) throw new Error('担当者名待ち');

const renderers = { home:homePage, register:registerPage, admin:adminPage, kitchen:kitchenPage, seats:seatsPage, customer:customerPage };
renderers[page]?.().catch(showError);

async function homePage(){
  app.innerHTML=pageShell(page,`<h1>ホーム</h1><div class="grid">${[['register','レジ','注文・会計・座席選択'],['kitchen','厨房','調理中の注文を確認'],['seats','座席管理','席状況の確認・空席化'],['customer','お客さん向け表示','会計内容を大きく表示'],['admin','管理','商品・在庫・座席数を編集']].map(([id,title,desc])=>`<a class="card home-card" href="./${id}.html"><strong>${title}</strong><span>${desc}</span></a>`).join('')}</div><div class="card" style="margin-top:20px"><h2>担当者</h2><div class="actions"><strong id="current-name">${escapeHtml(operator())}</strong><button id="change-name" class="btn">名前を変更</button></div></div>`);
  document.querySelector('#change-name').onclick=()=>{const name=prompt('新しい担当者名',operator());if(name?.trim()){setOperator(name);location.reload()}};
}

async function registerPage(){
  let products=[],cart={},cash='';
  const data=await api('getRegisterData');products=data.products;
  const draw=()=>{const entries=products.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]}));const total=entries.reduce((s,p)=>s+p.price*p.quantity,0);const change=cash!==''?Number(cash)-total:null;
    app.innerHTML=pageShell(page,`<h1>レジ</h1><div class="split"><section><h2>商品</h2><div class="products">${products.map(p=>`<button class="card product ${cart[p.id]?'in-cart':''}" data-add="${p.id}" ${p.stock<=0?'disabled':''}><strong>${escapeHtml(p.name)}</strong><span>${money(p.price)}</span><small>在庫 ${p.stock}</small></button>`).join('')}</div></section><aside class="card"><h2>注文内容</h2><div>${entries.length?entries.map(p=>`<div class="cart-row"><div><strong>${escapeHtml(p.name)}</strong><br>${money(p.price*p.quantity)}</div><div class="quantity"><button data-minus="${p.id}">−</button><b>${p.quantity}</b><button data-add="${p.id}" ${p.quantity>=p.stock?'disabled':''}>＋</button></div></div>`).join(''):'<p class="empty">商品を選んでください</p>'}</div><div class="field"><label>預かり金</label><input id="cash" inputmode="numeric" type="number" min="0" value="${escapeHtml(cash)}"></div><div class="money-panel"><div class="money-line"><span>合計</span><strong>${money(total)}</strong></div><div class="money-line"><span>預かり金</span><strong>${cash===''?'—':money(cash)}</strong></div><div class="money-line"><span>おつり</span><strong>${change===null?'—':money(change)}</strong></div></div><button id="to-seat" class="btn primary" style="width:100%" ${!entries.length||change<0||cash===''?'disabled':''}>座席を選ぶ</button><button id="clear" class="btn" style="width:100%;margin-top:9px">取消</button></aside></div>`);
    document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const id=b.dataset.add;const p=products.find(x=>x.id===id);cart[id]=Math.min((cart[id]||0)+1,p.stock);draw();sync()});document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{cart[b.dataset.minus]--;if(!cart[b.dataset.minus])delete cart[b.dataset.minus];draw();sync()});document.querySelector('#cash').oninput=e=>{cash=e.target.value;draw();sync()};document.querySelector('#clear').onclick=()=>{cart={};cash='';draw();sync()};document.querySelector('#to-seat').onclick=chooseSeat;
  };
  let syncTimer;function sync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{const items=products.filter(p=>cart[p.id]).map(p=>({name:p.name,price:p.price,quantity:cart[p.id]}));const total=items.reduce((s,x)=>s+x.price*x.quantity,0);api('updateDisplay',{operator:operator(),display:{phase:'checkout',items,total,cash:Number(cash||0),change:Number(cash||0)-total}}).catch(showError)},250)}
  async function chooseSeat(){try{const seats=await api('getSeats');const free=seats.filter(s=>s.status==='空席');if(!free.length)throw new Error('空席がありません');const html=`<div class="grid">${free.map(s=>`<button class="btn vacant seat-choice" data-seat="${s.number}">席 ${s.number}</button>`).join('')}</div>`;const d=document.createElement('dialog');d.innerHTML=`<h2>座席を選択</h2>${html}<button class="btn cancel" style="margin-top:15px">キャンセル</button>`;document.body.append(d);d.showModal();d.querySelector('.cancel').onclick=()=>{d.close();d.remove()};d.querySelectorAll('.seat-choice').forEach(b=>b.onclick=async()=>{const seat=Number(b.dataset.seat);b.disabled=true;try{const items=products.filter(p=>cart[p.id]).map(p=>({productId:p.id,quantity:cart[p.id]}));const result=await api('createOrder',{operator:operator(),seatNumber:seat,cash:Number(cash),items});d.close();d.remove();alert(`注文番号 ${result.orderNumber} を確定しました`);cart={};cash='';const refreshed=await api('getRegisterData');products=refreshed.products;draw()}catch(e){b.disabled=false;showError(e)}})}catch(e){showError(e)}}
  draw();sync();
}

async function kitchenPage(){app.innerHTML=pageShell(page,'<h1>厨房</h1><div id="orders"></div>');const host=document.querySelector('#orders');async function refresh(){try{const orders=await api('getKitchenOrders');host.innerHTML=orders.length?`<div class="grid">${orders.map(o=>`<article class="card order-card"><div class="order-head"><div><div class="order-number">#${o.orderNumber}</div><b>席 ${o.seatNumber}</b></div><span class="elapsed" data-at="${o.orderedAt}"></span></div><p>注文 ${time(o.orderedAt)}</p><ul class="items">${o.items.map(i=>`<li><strong>${escapeHtml(i.name)} × ${i.quantity}</strong></li>`).join('')}</ul><button class="btn blue serve" data-order="${o.orderNumber}">提供済み</button></article>`).join('')}</div>`:'<div class="card empty">調理中の注文はありません</div>';host.querySelectorAll('.serve').forEach(b=>b.onclick=async()=>{if(!await confirmDialog(`注文 #${b.dataset.order}`,'<p>提供済みに変更します。</p>','提供済みにする'))return;b.disabled=true;try{await api('serveOrder',{operator:operator(),orderNumber:Number(b.dataset.order)});refresh()}catch(e){b.disabled=false;showError(e)}});updateElapsed()}catch(e){showError(e)}}function updateElapsed(){document.querySelectorAll('[data-at]').forEach(el=>{const mins=Math.max(0,Math.floor((Date.now()-new Date(el.dataset.at))/60000));el.textContent=`${mins}分経過`})}await refresh();setInterval(refresh,5000);setInterval(updateElapsed,10000)}

async function seatsPage(){app.innerHTML=pageShell(page,'<h1>座席管理</h1><div id="seats"></div>');const host=document.querySelector('#seats');async function refresh(){try{const seats=await api('getSeats');host.innerHTML=`<div class="grid">${seats.map(s=>`<button class="card seat-card ${statusClass(s.status)}" data-seat="${s.number}"><strong>席 ${s.number}</strong><p>${s.status}</p><p>注文 ${s.orderNumber?'#'+s.orderNumber:'—'}</p><p>${time(s.orderedAt)}</p></button>`).join('')}</div>`;host.querySelectorAll('[data-seat]').forEach(b=>b.onclick=()=>detail(seats.find(s=>s.number===Number(b.dataset.seat))))}catch(e){showError(e)}}async function detail(s){const canClear=s.status!=='空席';const ok=await confirmDialog(`席 ${s.number}`,`<p><span class="status ${statusClass(s.status)}">${s.status}</span></p><p>注文番号: ${s.orderNumber?'#'+s.orderNumber:'—'}<br>注文時間: ${time(s.orderedAt)}</p>${canClear?'<p>お客さんの帰宅を確認してから空席に戻してください。</p>':''}`,canClear?'空席に戻す':'閉じる');if(ok&&canClear){try{await api('clearSeat',{operator:operator(),seatNumber:s.number});refresh()}catch(e){showError(e)}}}await refresh();setInterval(refresh,5000)}

async function adminPage(){app.innerHTML=pageShell(page,'<h1>管理</h1><div id="admin"></div>');const host=document.querySelector('#admin');async function refresh(){const d=await api('getAdminData');host.innerHTML=`<section class="card"><h2>商品管理</h2><div class="table-wrap"><table class="table"><thead><tr><th>商品名</th><th>価格</th><th>在庫</th><th></th></tr></thead><tbody>${d.products.map(p=>`<tr data-id="${p.id}"><td><input name="name" value="${escapeHtml(p.name)}"></td><td><input name="price" type="number" min="0" value="${p.price}"></td><td><input name="stock" type="number" min="0" value="${p.stock}"></td><td><button class="btn save">保存</button></td></tr>`).join('')}<tr><td><input id="new-name" placeholder="新商品名"></td><td><input id="new-price" type="number" min="0" value="0"></td><td><input id="new-stock" type="number" min="0" value="0"></td><td><button id="add-product" class="btn primary">追加</button></td></tr></tbody></table></div></section><section class="card" style="margin-top:20px"><h2>座席設定</h2><div class="field"><label>座席数</label><input id="seat-count" type="number" min="1" max="200" value="${d.seatCount}"></div><button id="save-seats" class="btn primary">座席数を保存</button><p class="muted">使用中の座席を減らすことはできません。</p></section>`;host.querySelectorAll('.save').forEach(b=>b.onclick=async()=>{const row=b.closest('tr');await run(b,()=>api('saveProduct',{operator:operator(),product:{id:row.dataset.id,name:row.querySelector('[name=name]').value,price:Number(row.querySelector('[name=price]').value),stock:Number(row.querySelector('[name=stock]').value)}}))});document.querySelector('#add-product').onclick=e=>run(e.target,async()=>{await api('saveProduct',{operator:operator(),product:{name:document.querySelector('#new-name').value,price:Number(document.querySelector('#new-price').value),stock:Number(document.querySelector('#new-stock').value)}});refresh()});document.querySelector('#save-seats').onclick=e=>run(e.target,()=>api('setSeatCount',{operator:operator(),count:Number(document.querySelector('#seat-count').value)}))}async function run(button,fn){button.disabled=true;try{await fn();alert('保存しました')}catch(e){showError(e)}finally{button.disabled=false}}await refresh()}

async function customerPage(){app.innerHTML=pageShell(page,'<div id="customer" class="customer-box"><h1>いらっしゃいませ</h1></div>');const host=document.querySelector('#customer');let last='';async function refresh(){try{const d=await api('getDisplay');const key=JSON.stringify(d);if(key===last)return;last=key;if(!d||d.phase==='idle')host.innerHTML='<h1>いらっしゃいませ</h1><p class="muted">ご注文をお伺いします</p>';else if(d.phase==='complete')host.innerHTML=`<h1>ありがとうございました</h1><p>注文番号</p><div class="order-number">${d.orderNumber}</div><h2>席 ${d.seatNumber}</h2>`;else host.innerHTML=`<h1>ご注文内容</h1><div class="card"><div class="table-wrap"><table class="table"><tbody>${d.items.map(i=>`<tr><td>${escapeHtml(i.name)}</td><td>× ${i.quantity}</td><td>${money(i.price*i.quantity)}</td></tr>`).join('')}</tbody></table></div><div class="money-panel"><div class="money-line"><span>合計</span><strong>${money(d.total)}</strong></div><div class="money-line"><span>預かり金</span><strong>${money(d.cash)}</strong></div><div class="money-line"><span>おつり</span><strong>${money(d.change)}</strong></div></div></div>`}catch(e){showError(e)}}await refresh();setInterval(refresh,1000)}
